 const htmlQuestions = [
  {
    question: "What is the SI unit of force?",
    option1: "Joule",
    option2: "Newton",
    option3: "Watt",
    option4: "Pascal",
    correctOption: "Newton",
  },
  {
    question: "Which law states that 'An object in motion stays in motion unless acted upon by an external force'?",
    option1: "Newton's First Law",
    option2: "Newton's Second Law",
    option3: "Newton's Third Law",
    option4: "Law of Gravitation",
    correctOption: "Newton's First Law",
  },
  {
    question: "What is the acceleration due to gravity on Earth?",
    option1: "9.8 m/s²",
    option2: "8.9 m/s²",
    option3: "10 m/s²",
    option4: "9.2 m/s²",
    correctOption: "9.8 m/s²",
  },
  {
    question: "Which physical quantity is defined as mass per unit volume?",
    option1: "Density",
    option2: "Pressure",
    option3: "Force",
    option4: "Velocity",
    correctOption: "Density",
  },
  {
    question: "What is the SI unit of work?",
    option1: "Newton",
    option2: "Joule",
    option3: "Watt",
    option4: "Meter",
    correctOption: "Joule",
  },
  {
    question: "Which force is responsible for keeping planets in orbit around the sun?",
    option1: "Magnetic force",
    option2: "Friction",
    option3: "Gravitational force",
    option4: "Electrostatic force",
    correctOption: "Gravitational force",
  },
  {
    question: "Which of the following is a vector quantity?",
    option1: "Mass",
    option2: "Speed",
    option3: "Velocity",
    option4: "Temperature",
    correctOption: "Velocity",
  },
  {
    question: "Which of the following is a non-contact force?",
    option1: "Friction",
    option2: "Normal Force",
    option3: "Gravitational Force",
    option4: "Tension",
    correctOption: "Gravitational Force",
  },
  {
    question: "Which Newton's law explains the principle of a rocket launch?",
    option1: "First Law",
    option2: "Second Law",
    option3: "Third Law",
    option4: "Law of Gravitation",
    correctOption: "Third Law",
  },
  {
    question: "What does a speed-time graph with a horizontal line represent?",
    option1: "Increasing speed",
    option2: "Decreasing speed",
    option3: "Constant speed",
    option4: "Object at rest",
    correctOption: "Constant speed",
  },
  {
    question: "What is the SI unit of power?",
    option1: "Watt",
    option2: "Newton",
    option3: "Joule",
    option4: "Pascal",
    correctOption: "Watt",
  },
  {
    question: "Which type of energy is stored in a stretched rubber band?",
    option1: "Kinetic Energy",
    option2: "Potential Energy",
    option3: "Thermal Energy",
    option4: "Chemical Energy",
    correctOption: "Potential Energy",
  },
  {
    question: "What is the force that opposes motion between two surfaces in contact?",
    option1: "Tension",
    option2: "Friction",
    option3: "Gravitational Force",
    option4: "Magnetic Force",
    correctOption: "Friction",
  },
  {
    question: "What is the unit of pressure?",
    option1: "Joule",
    option2: "Newton",
    option3: "Pascal",
    option4: "Watt",
    correctOption: "Pascal",
  },
  {
    question: "What does the slope of a distance-time graph represent?",
    option1: "Acceleration",
    option2: "Velocity",
    option3: "Force",
    option4: "Power",
    correctOption: "Velocity",
  },
  {
    question: "Which phenomenon causes a moving object to resist change in motion?",
    option1: "Friction",
    option2: "Gravity",
    option3: "Inertia",
    option4: "Momentum",
    correctOption: "Inertia",
  },
  {
    question: "What is the formula for momentum?",
    option1: "Force × Time",
    option2: "Mass × Velocity",
    option3: "Work ÷ Time",
    option4: "Distance × Time",
    correctOption: "Mass × Velocity",
  },
  {
    question: "Which of the following is an example of simple harmonic motion?",
    option1: "Car moving on a straight road",
    option2: "Earth orbiting the Sun",
    option3: "Pendulum swinging",
    option4: "Ball rolling down a hill",
    correctOption: "Pendulum swinging",
  },
  {
    question: "What is the value of 1 horsepower in watts?",
    option1: "550 W",
    option2: "746 W",
    option3: "1000 W",
    option4: "1500 W",
    correctOption: "746 W",
  },
  {
    question: "What is the main function of a simple machine?",
    option1: "Increase work",
    option2: "Reduce energy consumption",
    option3: "Make work easier",
    option4: "Convert energy",
    correctOption: "Make work easier",
  },
  {
    question: "Which of the following is a scalar quantity?",
    option1: "Velocity",
    option2: "Displacement",
    option3: "Force",
    option4: "Speed",
    correctOption: "Speed",
  },
  {
    question: "What does the first law of thermodynamics state?",
    option1: "Energy cannot be created or destroyed",
    option2: "Entropy always increases",
    option3: "Heat energy is the only form of energy",
    option4: "Work done is always negative",
    correctOption: "Energy cannot be created or destroyed",
  },
  {
    question: "What type of energy is possessed by an object in motion?",
    option1: "Potential Energy",
    option2: "Thermal Energy",
    option3: "Kinetic Energy",
    option4: "Nuclear Energy",
    correctOption: "Kinetic Energy",
  },
  {
    question: "Which force is responsible for the floating of objects in water?",
    option1: "Gravitational Force",
    option2: "Buoyant Force",
    option3: "Magnetic Force",
    option4: "Frictional Force",
    correctOption: "Buoyant Force",
  },
  {
    question: "What happens to an object when balanced forces act on it?",
    option1: "It moves in the direction of the greater force",
    option2: "It moves in the opposite direction",
    option3: "It remains stationary or continues moving at constant velocity",
    option4: "It accelerates",
    correctOption: "It remains stationary or continues moving at constant velocity",
  }
    // {
    //   question: "Which HTML element defines navigation links?",
    //   option1: "<nav>",
    //   option2: "<navigate>",
    //   option3: "<navigate>",
    //   option4: "<navlink>",
    //   correctOption: "<nav>",
    // },
    // {
    //   question: "What is the correct HTML element for playing video files?",
    //   option1: "<media>",
    //   option2: "<video>",
    //   option3: "<movie>",
    //   option4: "<film>",
    //   correctOption: "<video>",
    // },
    // {
    //   question: "How can you make a numbered list?",
    //   option1: "<list>",
    //   option2: "<dl>",
    //   option3: "<ul>",
    //   option4: "<ol>",
    //   correctOption: "<ol>",
    // },
    // {
    //   question:
    //     "Which HTML element is used to specify a footer for a document or section?",
    //   option1: "<bottom>",
    //   option2: "<footer>",
    //   option3: "<foot>",
    //   option4: "<section>",
    //   correctOption: "<footer>",
    // },
    // {
    //   question: "What is the correct HTML element for inserting an image?",
    //   option1: "<img>",
    //   option2: "<image>",
    //   option3: "<pic>",
    //   option4: "<photo>",
    //   correctOption: "<img>",
    // },
    // {
    //   question: "Which doctype is correct for HTML5?",
    //   option1: "<!DOCTYPE html>",
    //   option2: "<!DOCTYPE HTML5>",
    //   option3: '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 5.0//EN">',
    //   option4: "<!DOCTYPE html5>",
    //   correctOption: "<!DOCTYPE html>",
    // },
    // {
    //   question: "Who is making the Web standards?",
    //   option1: "Google",
    //   option2: "The World Wide Web Consortium",
    //   option3: "Microsoft",
    //   option3: "Apple",
    //   correctOption: "The World Wide Web Consortium",
    // },
    // {
    //   question: "Which character is used to indicate an end tag?",
    //   option1: "*",
    //   option2: "/",
    //   option3: "<",
    //   option4: "^",
    //   correctOption: "/",
    // },
    // {
    //   question: "How can you open a link in a new tab/browser window?",
    //   option1: '<a href="url" new>',
    //   option2: '<a href="url" target="_blank">',
    //   option3: '<a href="url" target="new">',
    //   option4: '<a href="url" target="new_tab">',
    //   correctOption: '<a href="url" target="_blank">',
    // },
    // {
    //   question: "Which HTML element is used to define important text?",
    //   option1: "<b>",
    //   option2: "<strong>",
    //   option3: "<i>",
    //   option4: "<important>",
    //   correctOption: "<strong>",
    // },
    // {
    //   question:
    //     "Which HTML element is used to define a block of text that has been quoted from another source?",
    //   option1: "<blockquote>",
    //   option2: "<q>",
    //   option3: "<quote>",
    //   option4: "<cite>",
    //   correctOption: "<blockquote>",
    // },
    // {
    //   question: "Which HTML element is used to define a table?",
    //   option1: "<tbl>",
    //   option2: "<table>",
    //   option3: "<t>",
    //   option4: "<tab>",
    //   correctOption: "<table>",
    // },
    // {
    //   question: "Which HTML element is used to define a list item?",
    //   option1: "<li>",
    //   option2: "<list>",
    //   option3: "<item>",
    //   option4: "<ul>",
    //   correctOption: "<li>",
    // },
    // {
    //   question: "Which HTML element is used to define a division or a section?",
    //   option1: "<div>",
    //   option2: "<sec>",
    //   option3: "<section>",
    //   option4: "<divs>",
    //   correctOption: "<div>",
    // },
    // {
    //   question: "What is the correct HTML for making a text input field?",
    //   option1: '<input type="textfield">',
    //   option2: "<textinput>",
    //   option3: "<textfield>",
    //   option4: '<input type="text">',
    //   correctOption: '<input type="text">',
    // },
    // {
    //   question:
    //     "Which HTML attribute is used to specify that an input field must be filled out?",
    //   option1: "placeholder",
    //   option2: "formvalidate",
    //   option3: "required",
    //   option4: "validate",
    //   correctOption: "required",
    // },
    // {
    //   question:
    //     "Which HTML element is used to define the document title that is shown in the browser’s title bar or on the page’s tab?",
    //   option1: "<meta>",
    //   option2: "<title>",
    //   option3: "<head>",
    //   option4: "<link>",
    //   correctOption: "<title>",
    // },
  ];
  
  const cssQuizQuestion = [
    {
      question: "Which HTML tag is used to define an internal style sheet?",
      option1: "<css>",
      option2: "<script>",
      option3: "<style>",
      option4: "<head>",
      correctOption: "<style>",
    },
    {
      question: "Which CSS property is used to change the background color?",
      option1: "color",
      option2: "bgcolor",
      option3: "background-color",
      option4: "bg-color",
      correctOption: "background-color",
    },
    {
      question: "What does CSS stand for?",
      option1: "Creative Style Sheets",
      option2: "Cascading Style Sheets",
      option3: "Computer Style Sheets",
      option4: "Colorful Style Sheets",
      correctOption: "Cascading Style Sheets",
    },
    {
      question: "Which property is used to change the text color of an element?",
      option1: "font-color",
      option2: "text-color",
      option3: "color",
      option4: "fgcolor",
      correctOption: "color",
    },
    {
      question: "Which CSS property controls the text size?",
      option1: "font-style",
      option2: "text-size",
      option3: "font-size",
      option4: "text-style",
      correctOption: "font-size",
    },
    {
      question: "Which property is used to make the text bold?",
      option1: "font-weight",
      option2: "text-decoration",
      option3: "font-style",
      option4: "font-bold",
      correctOption: "font-weight",
    },
    {
      question: "How do you make each word in a text start with a capital letter?",
      option1: "text-transform: capitalize",
      option2: "text-style: capitalize",
      option3: "transform: capitalize",
      option4: "font-transform: capitalize",
      correctOption: "text-transform: capitalize",
    },
    {
      question: "Which CSS property is used to change the font of an element?",
      option1: "font-family",
      option2: "font-weight",
      option3: "font-style",
      option4: "font-text",
      correctOption: "font-family",
    },
    {
      question: "Which property is used to align text to the center?",
      option1: "vertical-align",
      option2: "text-align",
      option3: "align-center",
      option4: "align-text",
      correctOption: "text-align",
    },
    {
      question: "How do you select an element with the id 'example' in CSS?",
      option1: "#example",
      option2: ".example",
      option3: "example",
      option4: "*example",
      correctOption: "#example",
    },
    {
      question: "How do you select all elements with the class name 'example'?",
      option1: "#example",
      option2: ".example",
      option3: "example",
      option4: "*example",
      correctOption: ".example",
    },
    {
      question: "Which property is used to change the spacing between letters?",
      option1: "spacing",
      option2: "letter-spacing",
      option3: "text-spacing",
      option4: "font-spacing",
      correctOption: "letter-spacing",
    },
    {
      question: "Which CSS property controls the space between lines of text?",
      option1: "line-height",
      option2: "text-height",
      option3: "spacing",
      option4: "line-spacing",
      correctOption: "line-height",
    },
    {
      question: "How do you display hyperlinks without an underline?",
      option1: "text-decoration: none",
      option2: "text-decoration: no-underline",
      option3: "hyperlink: none",
      option4: "text-underline: none",
      correctOption: "text-decoration: none",
    },
    {
      question: "How do you make a list that lists its items with squares?",
      option1: "list-style-type: square",
      option2: "list-style: square",
      option3: "list-type: square",
      option4: "list-style-shape: square",
      correctOption: "list-style-type: square",
    },
    {
      question: "Which property is used to set the margin of an element?",
      option1: "spacing",
      option2: "margin",
      option3: "padding",
      option4: "border",
      correctOption: "margin",
    },
    {
      question: "Which CSS property adds space inside the border of an element?",
      option1: "margin",
      option2: "padding",
      option3: "spacing",
      option4: "border-spacing",
      correctOption: "padding",
    },
    {
      question: "How do you make a border rounded?",
      option1: "border-shape: round",
      option2: "border-radius",
      option3: "border-round",
      option4: "border-curve",
      correctOption: "border-radius",
    },
    {
      question: "Which CSS property controls the order of flex items?",
      option1: "flex-direction",
      option2: "order",
      option3: "flex-order",
      option4: "item-order",
      correctOption: "order",
    },
    {
      question: "What is the default value of the position property?",
      option1: "static",
      option2: "relative",
      option3: "absolute",
      option4: "fixed",
      correctOption: "static",
    },
    {
      question: "How do you make a flex container?",
      option1: "display: flex",
      option2: "display: grid",
      option3: "display: block",
      option4: "display: inline",
      correctOption: "display: flex",
    },
    {
      question: "Which CSS property is used to hide an element?",
      option1: "visibility: hidden",
      option2: "display: none",
      option3: "opacity: 0",
      option4: "element-hide",
      correctOption: "display: none",
    },
    {
      question: "Which property is used to set the width of an element?",
      option1: "width",
      option2: "height",
      option3: "size",
      option4: "dimension",
      correctOption: "width",
    },
    {
      question: "Which property is used to control the overflow of an element?",
      option1: "overflow",
      option2: "scroll",
      option3: "hidden",
      option4: "auto",
      correctOption: "overflow",
    },
    {
      question: "How do you set the shadow of an element?",
      option1: "shadow",
      option2: "box-shadow",
      option3: "text-shadow",
      option4: "element-shadow",
      correctOption: "box-shadow",
    }
  ];
  

export {htmlQuestions , cssQuizQuestion};